### ISSUE TITLE
print.mully(g12) should be print(g12) in documentation

### ISSUE THREAD

**Issue by djinnome** [frankkramer-lab/mully#2]
Hi folks,

I was going through the `README.md` and when attempting to execute:

`print.mully(g12)`
I got the following error:

```
Error in print.mully(g12) : could not find function "print.mully"
```
However, the `print.mully` documentation  says the usage is:

```
## S3 method for class 'mully'
print(g)
```

and when I tried this, it worked, so the `README.md` should be updated accordingly

**Comment by frankkramer** [comment]
Thanks Jeremy for the reporty, we'll fix this with the next release!

--
Prof. Dr. Frank Kramer

IT-Infrastructure for Translational Medical Research
Faculty of Applied Computer Science
Faculty of Medicine
University Augsburg

Universitätsstraße 6a
86159 Augsburg

**Comment by djinnome** [comment]
Hi @frankkramer 

well, I am reviewing your paper right now, so I thought I would give you an opportunity to fix these issues before I submit my review.

Sincerely,

jeremy

**Comment by zaynabhammoud** [comment]
Thank you for the report !! Just fixed it.

**Comment by djinnome** [comment]
Thanks!  I pulled the latest and I see the changes.
