### ISSUE TITLE
No documentation for plot.mully

### ISSUE THREAD

**Issue by djinnome** [frankkramer-lab/mully#3]
Hi folks,

When I attempt to execute

```
plot.mully(g12, layout="scaled")
```
I get the following error:

```
Error in plot.mully(g12, layout = "scaled") : 
  could not find function "plot.mully"
```
I also noticed there was no documentation for `plot.mully`  when I tried to execute `help(plot.mully)`:

```
No documentation for ‘plot.mully’ in specified packages and libraries:
you could try ‘??plot.mully’
> ??plot.mully
> 
```

I am not an R programmer, but I am wondering if the problem is that the `NAMESPACE` file does not export any of the code in `mully_visualization`

**Comment by zaynabhammoud** [comment]
Hi,
I will look into that. Many thanks.

**Comment by djinnome** [comment]
Hi @zaynabhammoud 

No worries.   I could plot the graphs in 2D and 3D after I manually sourced the following files:

```
source('~/Projects/src/mully/R/mully_visualization.R', echo=TRUE)
source('~/Projects/src/mully/R/mully_layer.R', echo=TRUE)
source('~/Projects/src/mully/R/mully_constructor.R', echo=TRUE)
```

So, (at least in my hands) it appears as if calling
```
require(devtools)
install_github("frankkramer-lab/mully")
library(mully)
```
 does not currently source all the files it needs in order to run.

**Comment by zaynabhammoud** [comment]
Actually the problem is that I didn't export the visualization's functions. I will fix it ASAP. @djinnome 
Thanks again :)

**Comment by djinnome** [comment]
Hi @zaynabhammoud When I ran 

```
require(devtools)
install_github("frankkramer-lab/mully")
library(mully)
```
again, and execute
```
> plot.mully(g12, layout="scaled")
```
 I still get the error:

```
Error in plot.mully(g12, layout = "scaled") : 
  could not find function "plot.mully"
```

**Comment by zaynabhammoud** [comment]
@djinnome Should be working now. Please try it again and update me with any new error msgs.

**Comment by djinnome** [comment]
I restarted R, ran 

```
require(devtools)
install_github("frankkramer-lab/mully")
library(mully)
```
then created a graph
```
g1=mully()

  g1=addLayer(g1,c("protein","drug","gene"))

  g1=addNode(g1,"dr4","drug",attributes=list(effect="strong"))
  g1=addNode(g1,"dr5","drug",attributes=list(effect="strong"))
  g1=addNode(g1,"dr6","drug",attributes=list(effect="moderate"))

  g1=addNode(g1,"p1","protein")
  g1=addNode(g1,"p2","protein")
  g1=addNode(g1,"p3","protein")

  g1=addNode(g1,"g3","gene")
  g1=addNode(g1,"g4","gene")


  g1=addEdge(g1,nodeStart = "p2",nodeDest = "p3",attributes = list(name="interacts"))
  g1=addEdge(g1,nodeStart = "dr6",nodeDest = "g4",attributes = list(name="targets"))
```
Then tried to plot:

```
> plot.mully(g1, layout='scaled')
```
and I still get the same error:

```
Error in plot.mully(g1, layout = "scaled") : 
  could not find function "plot.mully"
```

**Comment by djinnome** [comment]
Perhaps the problem is that `plot.mully` and `plot.mully.3d` do not show up in the autogenerated `NAMESPACE` file:

```
# Generated by roxygen2: do not edit by hand

S3method(print,mully)
export(addEdge)
export(addLayer)
export(addNode)
export(exportCSV)
export(getEdgeAttributes)
export(getIDEdge)
export(getIDNode)
export(getLayer)
export(getLayersCount)
export(getNode)
export(getNodeAttributes)
export(importEdgesCSV)
export(importGraphCSV)
export(importLayersCSV)
export(importNodesCSV)
export(isLayer)
export(merge)
export(mully)
export(removeEdge)
export(removeLayer)
export(removeNode)
```

**Comment by djinnome** [comment]
I see that the `@export` directive is included in `plot.mully` in `mully/R/mully_visualization.R`. Did you perhaps forget to rerun roxygen?

(Again, this is a guess. I am not an R programmer)

**Comment by zaynabhammoud** [comment]
Actually in the latest push the functions are exported ... @djinnome

**Comment by djinnome** [comment]
Weird. I see that NAMESPACE now has export plot.mully,
```
S3method(plot,mully)
S3method(plot,mully.3d)
S3method(print,mully)
```

 but when I restart R, and then:
```
require(devtools)
install_github("frankkramer-lab/mully")
library(mully)
```


I still get the same error:

```
> plot.mully(g, layout="scaled")
Error in plot.mully(g, layout = "scaled") : 
  could not find function "plot.mully
```
When I try to `install_github` again, it says:
```
install_github("frankkramer-lab/mully")
Skipping install of 'mully' from a github remote, the SHA1 (738d631b) has not changed since last install.
  Use `force = TRUE` to force installation
> 
```

The SHA1 is 738d631b, which is the same as the latest commit.  Can you think of any reason it can't find `plot.mully`?

When I list the exports, this is what I get:

```
getNamespaceExports("mully")
 [1] "merge"             "removeNode"        "getLayersCount"    "exportCSV"        
 [5] "getLayer"          "importEdgesCSV"    "addLayer"          "getNodeAttributes"
 [9] "mully"             "getNode"           "getIDEdge"         "importLayersCSV"  
[13] "getIDNode"         "removeLayer"       "removeEdge"        "isLayer"          
[17] "addNode"           "importGraphCSV"    "importNodesCSV"    "addEdge"          
[21] "getEdgeAttributes"
> 
```

**Comment by djinnome** [comment]
Again, `plot.mully` works fine if I just `source('~/Projects/src/mully/R/mully_visualization.R')`

**Comment by zaynabhammoud** [comment]
Hi @djinnome ,
This might sound a little bit stupid, but I think the problem is with the functions' names. Since the standard S3 Method naming for a plot function is "plot"."name of the package", then plot.mully is considered plot, and plot.mully.3d cannot be called like this. So I would have to change the names of the functions. However, you can still call them now by using mully:::plot.mully(..) and mully:::plot.mully.3d(..).

**Comment by djinnome** [comment]
I see.  R is a weird language.  Would it be consistent with the manuscript and your documentation if you did not export `plot.mully` and `plot.mully.3d` as `S3` Methods, but just as regular functions?

**Comment by zaynabhammoud** [comment]
Well you don't choose how you export your functions, it depends on the form. As I am dealing with these functions as regular ones, the changing of the names would not affect the manuscript nor the documentation semantically, but just syntactically, so we would have to adjust the names in the manuscript. I suggest to use the Camel Case, so for example plotMully and plotMully3d.

**Comment by zaynabhammoud** [comment]
So I kept them as S3 Methods, you just call plot(g,..) instead of plot.mully(g,..) for 2D plots, and plot3d(g) instead of plot.mully.3d(g) for 3D plots.

**Comment by djinnome** [comment]
I like it. Seems like a nice robust solution.

**Comment by djinnome** [comment]
Hmm...looks like there is another issue that came up.

```
> plot3d(g)
Error in xyz.coords(x, y, z, xlab = xlabel, ylab = ylabel, zlab = zlabel,  : 
  'x' is a list, but does not have components 'x', 'y'  and 'z'
> 
```

Any sense you have as to what the problem might be?

**Comment by zaynabhammoud** [comment]
That's weird. I just tried it and I didn't get this error. Could you please show me the graph that you are trying to plot?

**Comment by djinnome** [comment]
Hey @zaynabhammoud 
Nevermind, I installed from the latest github and it is working just fine now.

Thanks so much for all your help.
